# This is a config for E2B sandbox template.
# You can use template ID (sg7997qmvmk6qrbfljp5) or template name (vibe-nextjs-dinotest) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-dinotest") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-dinotest") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-dinotest')

team_id = "f89eb68f-fba7-4f24-b54d-89e34f5fc3c4"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-dinotest"
template_id = "sg7997qmvmk6qrbfljp5"
